#!/usr/bin/env bash
# ============================================================================
# NEXA Exchange — One-Click Deployment Script
# ============================================================================
# Usage:
#   chmod +x deploy.sh && ./deploy.sh
#
# This script will:
#   1. Check all prerequisites (docker, go, etc.)
#   2. Configure environment variables
#   3. Start infrastructure (PostgreSQL, Redis, Kafka)
#   4. Run database migrations
#   5. Build all microservices
#   6. Start all services (matching-engine, api-gateway, wallet-service)
#   7. Verify health of all services
# ============================================================================

set -euo pipefail

# ── Colors ──────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
log_info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
log_ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

# ── Config ──────────────────────────────────────────────────────────────
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_DIR="$PROJECT_ROOT/build"
ENV_FILE="$PROJECT_ROOT/.env"
COMPOSE_FILE="$PROJECT_ROOT/deploy/docker/docker-compose.yml"

# Defaults (override via environment)
export JWT_SECRET="${JWT_SECRET:-nexa-deploy-secret-change-me}"
export JWT_ISSUER="${JWT_ISSUER:-nexa-exchange}"
export LISTEN_ADDR="${LISTEN_ADDR:-:8080}"
export GRPC_ADDR="${GRPC_ADDR:-:50051}"
export ENVIRONMENT="${ENVIRONMENT:-production}"
export POSTGRES_DSN="${POSTGRES_DSN:-postgres://nexa:nexa_dev@localhost:5432/nexa?sslmode=disable}"
export REDIS_ADDR="${REDIS_ADDR:-localhost:6379}"
export REDIS_PASSWORD="${REDIS_PASSWORD:-}"
export REDIS_DB="${REDIS_DB:-0}"
export KAFKA_BROKERS="${KAFKA_BROKERS:-localhost:9092}"
export KAFKA_TOPIC="${KAFKA_TOPIC:-nexa-exchange}"
export TRADING_PAIRS="${TRADING_PAIRS:-BTC/USDT,ETH/USDT,SOL/USDT,BNB/USDT,ADA/USDT}"
export ALCHEMY_API_KEY="${ALCHEMY_API_KEY:-}"
export LOG_LEVEL="${LOG_LEVEL:-info}"
export LOG_FORMAT="${LOG_FORMAT:-text}"

# ── Pre-flight checks ───────────────────────────────────────────────────
preflight() {
    echo ""
    echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
    echo -e "${BLUE}   NEXA Exchange — One-Click Deployment${NC}"
    echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
    echo ""

    local fail=0

    # Docker
    if ! command -v docker &>/dev/null; then
        log_error "Docker is not installed. Install: https://docs.docker.com/get-docker/"
        fail=1
    else
        log_ok "Docker $(docker --version | cut -d' ' -f3 | tr -d ',')"
    fi

    # Docker Compose
    if docker compose version &>/dev/null; then
        log_ok "Docker Compose v2"
        export COMPOSE_CMD="docker compose"
    elif command -v docker-compose &>/dev/null; then
        log_ok "Docker Compose v1"
        export COMPOSE_CMD="docker-compose"
    else
        log_error "Docker Compose not found"
        fail=1
    fi

    # Go
    if ! command -v go &>/dev/null; then
        log_error "Go is not installed. Install: https://go.dev/dl/"
        fail=1
    else
        log_ok "Go $(go version | grep -oP 'go\S+' | tr -d 'go')"
    fi

    # curl
    if ! command -v curl &>/dev/null; then
        log_warn "curl not found — health checks will be skipped"
    fi

    # Port conflicts
    for port in 5432 6379 2181 9092 8080 8082 50051; do
        if (ss -tlnp 2>/dev/null || netstat -tlnp 2>/dev/null) | grep -q ":$port "; then
            log_warn "Port $port is already in use — may cause conflicts"
        fi
    done

    if [ "$fail" -eq 1 ]; then
        echo ""
        log_error "Prerequisites missing. Aborting."
        exit 1
    fi
    echo ""
}

# ── Write .env file ─────────────────────────────────────────────────────
write_env() {
    if [ -f "$ENV_FILE" ] && [ "${ENVIRONMENT}" = "production" ]; then
        log_warn ".env already exists — backing up to .env.backup"
        cp "$ENV_FILE" "$ENV_FILE.backup"
    fi

    cat > "$ENV_FILE" <<-EOF
# NEXA Exchange — Auto-generated by deploy.sh
JWT_SECRET=${JWT_SECRET}
JWT_ISSUER=${JWT_ISSUER}
LISTEN_ADDR=${LISTEN_ADDR}
GRPC_ADDR=${GRPC_ADDR}
ENVIRONMENT=${ENVIRONMENT}
POSTGRES_DSN=${POSTGRES_DSN}
REDIS_ADDR=${REDIS_ADDR}
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_DB=${REDIS_DB}
KAFKA_BROKERS=${KAFKA_BROKERS}
KAFKA_TOPIC=${KAFKA_TOPIC}
TRADING_PAIRS=${TRADING_PAIRS}
ALCHEMY_API_KEY=${ALCHEMY_API_KEY}
LOG_LEVEL=${LOG_LEVEL}
LOG_FORMAT=${LOG_FORMAT}
EOF
    log_ok ".env file written"
}

# ── Start infrastructure ────────────────────────────────────────────────
start_infra() {
    log_info "Starting infrastructure (PostgreSQL, Redis, Kafka)..."
    $COMPOSE_CMD -f "$COMPOSE_FILE" up -d --wait --wait-timeout 120 2>&1 || {
        log_warn "docker compose --wait timed out. Checking container health..."
        $COMPOSE_CMD -f "$COMPOSE_FILE" ps
    }
    log_ok "Infrastructure services started"

    # Wait for PostgreSQL to be ready
    log_info "Waiting for PostgreSQL..."
    for i in $(seq 1 30); do
        if docker exec nexa-exchange-postgres-1 pg_isready -U nexa &>/dev/null 2>&1 || \
           docker exec $(docker ps --filter name=postgres -q | head -1) pg_isready -U nexa &>/dev/null 2>&1; then
            log_ok "PostgreSQL is ready"
            break
        fi
        if [ "$i" -eq 30 ]; then log_warn "PostgreSQL readiness check timed out — continuing"; fi
        sleep 2
    done
}

# ── Run migrations ──────────────────────────────────────────────────────
run_migrations() {
    log_info "Running database migrations..."
    (cd "$PROJECT_ROOT" && POSTGRES_DSN="$POSTGRES_DSN" go run ./scripts/migrate/main.go)
    log_ok "Migrations complete"
}

# ── Build services ──────────────────────────────────────────────────────
build_services() {
    log_info "Building microservices..."
    mkdir -p "$BUILD_DIR"
    (cd "$PROJECT_ROOT" && \
        CGO_ENABLED=0 go build -ldflags='-s -w' -o "$BUILD_DIR/api-gateway" ./cmd/api-gateway/ && \
        CGO_ENABLED=0 go build -ldflags='-s -w' -o "$BUILD_DIR/matching-engine" ./cmd/matching-engine/ && \
        CGO_ENABLED=0 go build -ldflags='-s -w' -o "$BUILD_DIR/wallet-service" ./cmd/wallet-service/)
    log_ok "All services built successfully"
}

# ── Start services ──────────────────────────────────────────────────────
start_services() {
    # Kill any existing instances
    for proc in matching-engine api-gateway wallet-service; do
        pkill -f "$BUILD_DIR/$proc" 2>/dev/null || true
    done
    sleep 1

    log_info "Starting Matching Engine..."
    (cd "$PROJECT_ROOT" && "$BUILD_DIR/matching-engine" &>/tmp/nexa-engine.log) &
    ENGINE_PID=$!
    sleep 2

    log_info "Starting API Gateway..."
    (cd "$PROJECT_ROOT" && "$BUILD_DIR/api-gateway" &>/tmp/nexa-api.log) &
    API_PID=$!
    sleep 1

    log_info "Starting Wallet Service..."
    (cd "$PROJECT_ROOT" && "$BUILD_DIR/wallet-service" &>/tmp/nexa-wallet.log) &
    WALLET_PID=$!

    echo "$ENGINE_PID" > /tmp/nexa-engine.pid
    echo "$API_PID" > /tmp/nexa-api.pid
    echo "$WALLET_PID" > /tmp/nexa-wallet.pid

    log_ok "All services started"
}

# ── Health checks ───────────────────────────────────────────────────────
health_check() {
    echo ""
    log_info "Running health checks..."
    sleep 3

    local all_ok=0
    local endpoints=(
        "http://localhost:8080/health:API Gateway"
        "http://localhost:8082/health:Wallet Service"
    )

    for ep in "${endpoints[@]}"; do
        local url="${ep%%:*}"
        local name="${ep##*:}"
        if curl -sf "$url" &>/dev/null; then
            log_ok "$name — $url ✓"
        else
            log_warn "$name — $url not responding yet"
            all_ok=1
        fi
    done

    # Check if engine process is running
    if [ -f /tmp/nexa-engine.pid ] && kill -0 "$(cat /tmp/nexa-engine.pid)" 2>/dev/null; then
        log_ok "Matching Engine — running ✓"
    else
        log_warn "Matching Engine process check failed"
        all_ok=1
    fi

    echo ""
    if [ "$all_ok" -eq 0 ]; then
        log_ok "All services are healthy!"
    else
        log_warn "Some services may not be fully ready — check logs in /tmp/nexa-*.log"
    fi
}

# ── Print summary ───────────────────────────────────────────────────────
print_summary() {
    echo ""
    echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
    echo -e "${GREEN}   NEXA Exchange — Deployment Complete${NC}"
    echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
    echo ""
    echo "  REST API:       http://localhost:8080"
    echo "  WebSocket:      ws://localhost:8080/ws"
    echo "  gRPC:           localhost:50051"
    echo "  Wallet Service: http://localhost:8082"
    echo ""
    echo "  Trading Pairs:  $TRADING_PAIRS"
    echo "  Environment:    $ENVIRONMENT"
    echo "  Data Dir:       $PROJECT_ROOT"
    echo ""
    echo "  Commands:"
    echo "    ./deploy.sh stop       Stop all services"
    echo "    ./deploy.sh restart    Restart all services"
    echo "    ./deploy.sh logs       Tail service logs"
    echo "    ./deploy.sh status     Check service status"
    echo ""
    echo -e "${YELLOW}  ┌─────────────────────────────────────────────────────┐${NC}"
    echo -e "${YELLOW}  │ IMPORTANT: Set ALCHEMY_API_KEY for wallet service!  │${NC}"
    echo -e "${YELLOW}  │ Get one at: https://www.alchemy.com/                │${NC}"
    echo -e "${YELLOW}  └─────────────────────────────────────────────────────┘${NC}"
    echo ""
}

# ── Stop services ───────────────────────────────────────────────────────
stop_services() {
    log_info "Stopping all services..."
    for pid_file in /tmp/nexa-engine.pid /tmp/nexa-api.pid /tmp/nexa-wallet.pid; do
        if [ -f "$pid_file" ]; then
            kill "$(cat "$pid_file")" 2>/dev/null || true
            rm -f "$pid_file"
        fi
    done
    log_ok "Services stopped"
}

# ── Show logs ───────────────────────────────────────────────────────────
show_logs() {
    echo "=== Matching Engine ==="
    tail -50 /tmp/nexa-engine.log 2>/dev/null || echo "(no logs)"
    echo ""
    echo "=== API Gateway ==="
    tail -50 /tmp/nexa-api.log 2>/dev/null || echo "(no logs)"
    echo ""
    echo "=== Wallet Service ==="
    tail -50 /tmp/nexa-wallet.log 2>/dev/null || echo "(no logs)"
}

# ── Show status ─────────────────────────────────────────────────────────
show_status() {
    echo "Process Status:"
    for pid_file in /tmp/nexa-engine.pid /tmp/nexa-api.pid /tmp/nexa-wallet.pid; do
        local name=$(basename "$pid_file" .pid)
        if [ -f "$pid_file" ] && kill -0 "$(cat "$pid_file")" 2>/dev/null; then
            echo "  $name: RUNNING (PID $(cat "$pid_file"))"
        else
            echo "  $name: STOPPED"
        fi
    done
    echo ""
    echo "Docker Containers:"
    $COMPOSE_CMD -f "$COMPOSE_FILE" ps 2>/dev/null || echo "  (not running)"
}

# ── Main ────────────────────────────────────────────────────────────────
main() {
    case "${1:-start}" in
        start)
            preflight
            write_env
            start_infra
            run_migrations
            build_services
            start_services
            health_check
            print_summary
            ;;
        stop)
            stop_services
            ;;
        restart)
            stop_services
            sleep 2
            main start
            ;;
        logs)
            show_logs
            ;;
        status)
            show_status
            ;;
        infra-up)
            start_infra
            ;;
        infra-down)
            $COMPOSE_CMD -f "$COMPOSE_FILE" down
            ;;
        *)
            echo "Usage: $0 {start|stop|restart|logs|status|infra-up|infra-down}"
            echo ""
            echo "  start      Full deployment (default)"
            echo "  stop       Stop all services"
            echo "  restart    Restart all services"
            echo "  logs       View service logs"
            echo "  status     Check service and infra status"
            echo "  infra-up   Start infrastructure only"
            echo "  infra-down Stop infrastructure"
            exit 1
            ;;
    esac
}

main "$@"