apiVersion: v1
kind: ConfigMap
metadata:
  name: nexa-config
  namespace: nexa
data:
  JWT_ISSUER: nexa-exchange
  LISTEN_ADDR: ":8080"
  ENVIRONMENT: production
  ALCHEMY_ETH_URL: "https://eth-mainnet.g.alchemy.com/v2/owtgBOQy-6ABQ9Pzd_7Nz"
  ALCHEMY_POLYGON_URL: "https://polygon-mainnet.g.alchemy.com/v2/owtgBOQy-6ABQ9Pzd_7Nz"
