apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nexa-api-gateway
  namespace: nexa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nexa-api-gateway
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: {type: Utilization, averageUtilization: 60}
    - type: Resource
      resource:
        name: memory
        target: {type: Utilization, averageUtilization: 70}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nexa-matching-engine
  namespace: nexa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nexa-matching-engine
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: {type: Utilization, averageUtilization: 60}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nexa-wallet-service
  namespace: nexa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nexa-wallet-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: {type: Utilization, averageUtilization: 70}
