package api

import (
	"errors"
	"math/big"
	"net/http"
	"strconv"

	"github.com/gin-gonic/gin"
	"github.com/WkT010/nexa-exchange/internal/wallet"
)

// WalletService is the subset of wallet.Service used by the HTTP layer. It is
// satisfied by *wallet.Service in production and by a fake in tests.
type WalletService interface {
	GetBalance(userID, asset string) (*wallet.Wallet, error)
	GetBalances(userID string) ([]*wallet.Wallet, error)
	Deposit(userID, asset string, amount *big.Float, txHash string) error
	Withdraw(userID, asset, address string, amount *big.Float) error
	ListTransactions(userID string, limit, offset int) ([]*wallet.Transaction, error)
}

// WalletHandler exposes the wallet HTTP API: balances, deposit address, withdraw
// and transaction history.
type WalletHandler struct {
	svc     WalletService
	clients map[string]wallet.BlockchainClient
}

func NewWalletHandler(svc WalletService, clients map[string]wallet.BlockchainClient) *WalletHandler {
	return &WalletHandler{svc: svc, clients: clients}
}

// GetBalances returns all wallet balances for the authenticated user.
// GET /api/v2/wallet/balances
func (h *WalletHandler) GetBalances(c *gin.Context) {
	uid, _ := c.Get("user_id")
	userID, _ := uid.(string)
	if userID == "" {
		c.JSON(http.StatusUnauthorized, gin.H{"error": "user not authenticated"})
		return
	}
	ws, err := h.svc.GetBalances(userID)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to load balances"})
		return
	}
	if ws == nil {
		ws = []*wallet.Wallet{}
	}
	result := make([]gin.H, len(ws))
	for i, w := range ws {
		result[i] = walletToJSON(w)
	}
	c.JSON(http.StatusOK, gin.H{"balances": result})
}

// GetBalance returns the wallet for a single asset.
// GET /api/v2/wallet/balances/:asset
func (h *WalletHandler) GetBalance(c *gin.Context) {
	uid, _ := c.Get("user_id")
	userID, _ := uid.(string)
	asset := c.Param("asset")
	if asset == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "asset required"})
		return
	}
	w, err := h.svc.GetBalance(userID, asset)
	if err != nil {
		if errors.Is(err, wallet.ErrWalletNotFound) {
			c.JSON(http.StatusNotFound, gin.H{"error": "wallet not found"})
			return
		}
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to load wallet"})
		return
	}
	c.JSON(http.StatusOK, walletToJSON(w))
}

// GetDepositAddress generates (or returns) a deposit address for an asset.
// POST /api/v2/wallet/deposit/address  { "asset": "BTC" }
//
// In production the address is generated by the on-chain wallet-service and
// watched for incoming deposits; this endpoint returns a fresh address from the
// configured blockchain client. For assets without a client (e.g. USDT issued
// internally), the asset symbol itself is returned as a placeholder.
func (h *WalletHandler) GetDepositAddress(c *gin.Context) {
	uid, _ := c.Get("user_id")
	userID, _ := uid.(string)
	var r struct {
		Asset string `json:"asset" binding:"required"`
	}
	if err := c.ShouldBindJSON(&r); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "asset required"})
		return
	}
	if client, ok := h.clients[r.Asset]; ok {
		addr, err := client.GenerateAddress()
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "address generation failed"})
			return
		}
		c.JSON(http.StatusOK, gin.H{"asset": r.Asset, "address": addr, "user_id": userID})
		return
	}
	c.JSON(http.StatusOK, gin.H{"asset": r.Asset, "address": "", "user_id": userID, "note": "manual deposit only"})
}

// Deposit credits the user's wallet. This is an internal/admin endpoint in
// production (deposits are normally detected by the wallet-service), but it is
// exposed for testing and integration.
// POST /api/v2/wallet/deposit  { "asset":"BTC","amount":"1.0","tx_hash":"..." }
func (h *WalletHandler) Deposit(c *gin.Context) {
	uid, _ := c.Get("user_id")
	userID, _ := uid.(string)
	var r struct {
		Asset  string `json:"asset" binding:"required"`
		Amount string `json:"amount" binding:"required"`
		TxHash string `json:"tx_hash"`
	}
	if err := c.ShouldBindJSON(&r); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "asset and amount required"})
		return
	}
	amt := new(big.Float)
	if _, _, err := amt.Parse(r.Amount, 10); err != nil || amt.Sign() <= 0 {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid amount"})
		return
	}
	if err := h.svc.Deposit(userID, r.Asset, amt, r.TxHash); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, gin.H{"status": "ok", "asset": r.Asset, "amount": r.Amount})
}

// Withdraw locks the funds and queues a withdrawal for the wallet-service to
// broadcast on-chain.
// POST /api/v2/wallet/withdraw  { "asset":"BTC","address":"...","amount":"0.5" }
func (h *WalletHandler) Withdraw(c *gin.Context) {
	uid, _ := c.Get("user_id")
	userID, _ := uid.(string)
	var r struct {
		Asset   string `json:"asset" binding:"required"`
		Address string `json:"address" binding:"required"`
		Amount  string `json:"amount" binding:"required"`
	}
	if err := c.ShouldBindJSON(&r); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "asset, address and amount required"})
		return
	}
	amt := new(big.Float)
	if _, _, err := amt.Parse(r.Amount, 10); err != nil || amt.Sign() <= 0 {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid amount"})
		return
	}
	if err := h.svc.Withdraw(userID, r.Asset, r.Address, amt); err != nil {
		switch {
		case errors.Is(err, wallet.ErrInsufficientBalance):
			c.JSON(http.StatusPaymentRequired, gin.H{"error": "insufficient balance"})
		case errors.Is(err, wallet.ErrInvalidAddress):
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid address"})
		case errors.Is(err, wallet.ErrUnsupportedAsset):
			c.JSON(http.StatusBadRequest, gin.H{"error": "unsupported asset"})
		default:
			c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		}
		return
	}
	c.JSON(http.StatusOK, gin.H{"status": "pending", "asset": r.Asset, "amount": r.Amount, "address": r.Address})
}

// ListTransactions returns the user's transaction history.
// GET /api/v2/wallet/transactions?limit=50&offset=0
func (h *WalletHandler) ListTransactions(c *gin.Context) {
	uid, _ := c.Get("user_id")
	userID, _ := uid.(string)
	limit, _ := strconv.Atoi(c.DefaultQuery("limit", "50"))
	if limit <= 0 || limit > 500 {
		limit = 50
	}
	offset, _ := strconv.Atoi(c.DefaultQuery("offset", "0"))
	if offset < 0 {
		offset = 0
	}
	txs, err := h.svc.ListTransactions(userID, limit, offset)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to list transactions"})
		return
	}
	if txs == nil {
		txs = []*wallet.Transaction{}
	}
	result := make([]gin.H, len(txs))
	for i, t := range txs {
		result[i] = txToJSON(t)
	}
	c.JSON(http.StatusOK, gin.H{"transactions": result, "limit": limit, "offset": offset})
}

// ListSupportedAssets returns the assets for which a blockchain client is
// registered (i.e. on-chain deposit/withdrawal is supported).
// GET /api/v2/wallet/assets
func (h *WalletHandler) ListSupportedAssets(c *gin.Context) {
	assets := make([]string, 0, len(h.clients))
	for a := range h.clients {
		assets = append(assets, a)
	}
	c.JSON(http.StatusOK, gin.H{"assets": assets})
}

func walletToJSON(w *wallet.Wallet) gin.H {
	return gin.H{
		"id":         w.ID,
		"user_id":    w.UserID,
		"asset":      w.Asset,
		"address":    w.Address,
		"balance":    safeFloatStr(w.Balance),
		"locked":     safeFloatStr(w.Locked),
		"available":  safeFloatStr(new(big.Float).Sub(w.Balance, w.Locked)),
		"created_at": w.CreatedAt,
		"updated_at": w.UpdatedAt,
	}
}

func txToJSON(t *wallet.Transaction) gin.H {
	return gin.H{
		"id":            t.ID,
		"user_id":       t.UserID,
		"wallet_id":     t.WalletID,
		"type":          t.Type.String(),
		"asset":         t.Asset,
		"amount":        safeFloatStr(t.Amount),
		"fee":           safeFloatStr(t.Fee),
		"status":        t.Status.String(),
		"tx_hash":       t.TxHash,
		"confirmations": t.Confirmations,
		"created_at":    t.CreatedAt,
	}
}
